version: '3.11'

services:
  db:
    container_name: app_db
    image: postgres:16-alpine
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg_data: